IMAGE_TAG_CONFIG_SERVER: "testing-image-1"
IMAGE_TAG_DISCOVERY_SERVER: "testing-image-2"
IMAGE_TAG_CUSTOMERS_SERVICE: "testing-image-3"
IMAGE_TAG_VISITS_SERVICE: "testing-image-4"
IMAGE_TAG_VETS_SERVICE: "testing-image-5"
IMAGE_TAG_API_GATEWAY: "testing-image-6"
IMAGE_TAG_ADMIN_SERVER: "testing-image-7"
IMAGE_TAG_HYSTRIX_DASHBOARD: "testing-image-8"
IMAGE_TAG_GRAFANA_SERVICE: "testing-image-9"
IMAGE_TAG_PROMETHEUS_SERVICE: "testing-image-10"
DNS_NAME: "ozistg.oaltinoluk.com"